### PR TITLE
Get + Create project api endpoint

### PR DESCRIPTION
**Pull request by kennethzhu88**

### CODE REVIEW

**Comment by kennethzhu88** [comment]
Branch out from Weiyang's MR, please review this after merging his MR first.

**Comment by cherrythia** [comment]
This has conflict and incomplete. You need any help?

**Comment by kennethzhu88** [comment]
@cherrythia resolved, please check again.

**Comment by kennethzhu88** [comment]
@cherrythia  seems base change to main, i will create a new MR after changing base.

**Pull request closed without merging**
